name: CI devops 2022 CPE
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
      - develop
  pull_request:
jobs:
  test-backend:
    runs-on: ubuntu-18.04
    steps:
    #checkout your github code using actions/checkout@v2.3.3
      - uses: actions/checkout@v2.3.3
    #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
#finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file ./java/simple-api-main/simple-api


# define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
  # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
  # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : Login to DockerHub
        run : docker login -u ${{ secrets.USER }} -p ${{ secrets.ACCESTOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
      # relative path to the place where source code withDockerfile is located
          context: ./java
# Note: tags has to be all lower-case
          tags: ${{secrets.USER}}/java3:java
          push: ${{ github.ref == 'refs/heads/main' }}
    
    
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./database
          tags: ${{secrets.USER}}/database:database
          push: ${{ github.ref == 'refs/heads/main' }}
    
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          context: ./apache
          tags: ${{secrets.USER}}/apache:apache
          push: ${{ github.ref == 'refs/heads/main' }}
    
    
